# Generated by Django 4.0.2 on 2022-02-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_belongs_to_collection_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
