# Generated by Django 4.0.2 on 2022-02-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_collection_featured_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'price', 'inventory']},
        ),
    ]
