# Generated by Django 4.0.2 on 2022-02-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
    ]
