# Generated by Django 4.0.2 on 2022-02-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
