# Generated by Django 4.0.2 on 2022-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_last_updated_product_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', max_length=300),
            preserve_default=False,
        ),
    ]
