# Generated by Django 4.0.2 on 2022-02-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_id',
        ),
    ]
