# Generated by Django 4.0.2 on 2022-02-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_email_customer_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_id',
            new_name='email',
        ),
    ]
